language: python
sudo: false
python: 3.5
env:
  - TOX_ENV=py27-django1.6.X-djangocelery3.1.X
  - TOX_ENV=py27-django1.7.X-djangocelery3.1.X
  - TOX_ENV=py27-django1.8.X-djangocelery3.1.X
  - TOX_ENV=py27-django1.9.X-djangocelery3.1.X
  - TOX_ENV=py35-django1.8.X-djangocelery3.1.X
  - TOX_ENV=py35-django1.9.X-djangocelery3.1.X
  - TOX_ENV=py27-django1.6.X-celery3.1.X
  - TOX_ENV=py27-django1.7.X-celery3.1.X
  - TOX_ENV=py27-django1.8.X-celery3.1.X
  - TOX_ENV=py27-django1.9.X-celery3.1.X
  - TOX_ENV=py35-django1.8.X-celery3.1.X
  - TOX_ENV=py35-django1.9.X-celery3.1.X
  - TOX_ENV=flake8
install: pip install tox
script: tox -e $TOX_ENV
